export const INTERESTS = [
  "technology", "programming", "webdevelopment", "mobiledevelopment", "datascience",
  "machinelearning", "artificialintelligence", "blockchain", "cryptocurrency", "nfts",
  "uxui", "design", "productdesign", "photography", "videography", "film",
  "music", "classical", "jazz", "hiphop", "electronic", "indie", "kpop", "rnb",
  "podcasts", "books", "writing", "poetry", "comics", "manga", "anime",
  "movies", "romcom", "documentary", "theater", "standup", "comedy",
  "gaming", "esports", "boardgames", "tabletop", "rpg", "cosplay",
  "sports", "football", "basketball", "soccer", "running", "cycling", "swimming",
  "fitness", "yoga", "meditation", "hiking", "camping", "climbing",
  "travel", "backpacking", "vanlife", "food", "cooking", "baking", "mixology",
  "coffee", "tea", "wine", "beer", "cocktails",
  "fashion", "streetwear", "sneakers", "luxury", "beauty",
  "art", "illustration", "streetart", "sculpture", "crafts", "diy",
  "home", "homedecor", "interiordesign", "architecture", "gardening",
  "cars", "motorcycles", "trucks", "evs", "mechanics",
  "pets", "dogs", "cats", "aquarium", "birds",
  "health", "wellness", "nutrition", "mentalhealth", "parenting",
  "education", "learning", "languages", "history", "science", "space", "astronomy",
  "sustainability", "climate", "vegan", "vegetarian", "permaculture",
  "business", "startups", "entrepreneurship", "productivity", "leadership",
  "finance", "personalfinance", "investing", "stockmarket", "realestate",
  "marketing", "socialmedia", "contentcreation", "influencer",
  "career", "freelancing", "remote", "digitalnomad",
  "techgadgets", "smarthome", "hardware", "robotics",
  "collecting", "antiques", "collectibles", "tradingcards",
  "hobbies", "painting", "knitting", "woodworking", "modelbuilding",
  "other", "random", "memes", "community"
];